### ISSUE TITLE
Question: parallels of cpix with the format "portable-secret" uses

### ISSUE THREAD

**Issue by dumblob** [unifiedstreaming/pycpix#14]
I wonder if you see any parallels between cpix and the "outputs" (I hesitate to call it a format) tools like https://github.com/mprimi/portable-secret/ use?

Any advantages of cpix over such ad-hoc formats?

Thanks for your thoughts!

**Comment by markogle** [comment]
I don't think they are really comparable, CPIX is designed explicitly for transferring specific information (DRM keys and related signalling) between systems in media processing workflows.

**Comment by dumblob** [comment]
Ok, thanks!
